# Run this docker-compose file through envsubst. Example
# #!/bin/bash
# export INJECT_API_URL=
# export INJECT_PG_HOST=
# export INJECT_PG_PORT=
# export INJECT_PG_USER=
# export INJECT_PG_PASS=
# envsubst < docker-compose.deploy.yml > docker-compose.yml
version: '3'
services:
  aus-frontend:
    restart: unless-stopped
    build: 
      context: .
      dockerfile: Dockerfile.frontend
      args:
        - API_URL=$INJECT_API_URL
    ports:
      - '5000:5000'
    networks:
      - auspohzt
  aus-api:
    depends_on: 
      aus-db-migrate:
        condition: service_started
    restart: unless-stopped
    build: 
      context: .
      dockerfile: Dockerfile.api
    ports:
      - '4000:4000'
    env_file: .env
    environment:
      - ENABLE_AUTH=false
      - AUTH_COOKIE_NAME=bogan-auth
      - HMAC_SECRET=correct battery horse staple
      - API_URL=$INJECT_API_URL
      - API_TOKEN=eyJhbGciOiJIUzI1NiJ9.YWRtaW4.FeUPkoBVJl6ja_oogZ1GZ-X0lkOyTTPJ_YipSEj8-9E
      - WEB_PASSWORD=$INJECT_ADMIN_PASS
      - DIGITAL_API=https://digitalapi.auspost.com.au
      - API_KEY=
      - PORT=4000
      - PG_DATABASE=auspohzt
    networks:
      - auspohzt
  aus-db-migrate:
    command: npm run migrate --env target
    build: 
      context: .
      dockerfile: Dockerfile.dbmigrate
    env_file: .env
    environment:
      - PG_DATABASE=auspohzt
    networks:
      - auspohzt
networks:
  auspohzt:
